{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-classo
  version: {{ version }}

source:
  path: ../..

build:
  script: |
    make VERBOSE=1
    make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - classo
    - pandas {{ pandas }}
    - zarr>=2.11.1
    - pytest>=7.0.1
    - jinja2
    - biom-format
    - q2-types {{ qiime2_epoch }}.*
    - qiime2 {{ qiime2_epoch }}.*

about:
  home: https://github.com/bio-datascience/q2-classo-latest
  license: BSD-3-Clause
  license_family: BSD